### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#666]
### Pre-requisites

- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

### What version of the AaC package are you using? Check your version with the command: aac version.

0.2.0

### Description

While updating unit tests for validators in my 3rd party plugin, I realized everything works for good data but errors out for bad data.  Other unit tests confirm the validator itself works, so there's something happening in the "core" validator.  This assertion is further supported by the fact that the same behavior is seen on 2 different validators.

### Reproduction steps

```bash
Write a validator unit test that executes the following function:

with validated_definitions(parse(yaml_str)) as result:
        return result

Set yaml_str to a valid model and it will work.  Set yaml_str to an invalid model it it will error out (literal stack trace sort of error, not a validation failure as expected).
```

### Screenshots

```bash
Output from first validator test:

tox
.pkg: _optional_hooks> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py: install_package> python -I -m pip install --force-reinstall --no-deps /home/jdblack/documents/repos/AaC-BOM/src/.tox/.tmp/package/173/aac-bom-0.0.1.tar.gz
py: commands[0]> nose2 -c tox.ini
WARNING:root:The file /home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/persistence/../state.json could not be imported to initialize the active context.
..E.......
======================================================================
ERROR: test_core_validate_circular_site_reference (test_circular_references.TestCircularReferencesValicator.test_core_validate_circular_site_reference)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jdblack/documents/repos/AaC-BOM/src/tests/test_circular_references.py", line 39, in test_core_validate_circular_site_reference
    result = run_core_validate(CIRCULAR_SITE_REF)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/tests/test_utils.py", line 34, in run_core_validate
    with validated_definitions(parse(yaml_str)) as result:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/validate/_validate.py", line 52, in validated_definitions
    yield _with_validation(definitions, get_active_context())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/validate/_validate.py", line 83, in _with_validation
    raise ValidationError(result.get_messages_as_string())
aac.validate._validation_error.ValidationError: 
Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for My_New_Apartment in <string> on line 3

Validation ERROR from 'No circular material references' in <string>. Circular site reference detected for Living_Room in <string> on line 13

----------------------------------------------------------------------
Ran 10 tests in 6.178s

FAILED (errors=1)
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
material_model/material_model_impl.py            125     12    90.40%   44, 106, 113-117, 152-156
material_model/__init__.py                        34      1    97.06%   82
material_model/no_circular_references.py          56      0   100.00%
material_model/referenced_material_exists.py      46      0   100.00%
-------------------------------------------------------------------------------
TOTAL                                            261     13    95.02%

py: exit 1 (6.65 seconds) /home/jdblack/documents/repos/AaC-BOM/src> nose2 -c tox.ini pid=22424
.pkg: _exit> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: FAIL code 1 (7.71=setup[1.06]+cmd[6.65] seconds)
  evaluation failed :( (7.75 seconds)
```

Output from second validator test:
```
tox
.pkg: _optional_hooks> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py: install_package> python -I -m pip install --force-reinstall --no-deps /home/jdblack/documents/repos/AaC-BOM/src/.tox/.tmp/package/176/aac-bom-0.0.1.tar.gz
py: commands[0]> nose2 -c tox.ini
WARNING:root:The file /home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/persistence/../state.json could not be imported to initialize the active context.
.......E...
======================================================================
ERROR: test_core_validate_bad_part_reference (test_referenced_material_exists.TestReferencedMaterialValidator.test_core_validate_bad_part_reference)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jdblack/documents/repos/AaC-BOM/src/tests/test_referenced_material_exists.py", line 35, in test_core_validate_bad_part_reference
    result = run_core_validate(BAD_PART_MATERIAL_REFERENCE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/tests/test_utils.py", line 34, in run_core_validate
    with validated_definitions(parse(yaml_str)) as result:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/validate/_validate.py", line 52, in validated_definitions
    yield _with_validation(definitions, get_active_context())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdblack/documents/repos/AaC-BOM/src/.tox/py/lib/python3.11/site-packages/aac/validate/_validate.py", line 83, in _with_validation
    raise ValidationError(result.get_messages_as_string())
aac.validate._validation_error.ValidationError: 
Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Referenced materials exist' in <string>. Cannot find part-ref target Arm_Chair_BROKEN in <string> on line 38

Validation ERROR from 'Validate Reference Primitives' in <string>. Arm_Chair_BROKEN is not a valid reference to a definition.

----------------------------------------------------------------------
Ran 11 tests in 7.437s

FAILED (errors=1)
Name                                           Stmts   Miss     Cover   Missing
-------------------------------------------------------------------------------
material_model/material_model_impl.py            125     12    90.40%   44, 106, 113-117, 152-156
material_model/__init__.py                        34      1    97.06%   82
material_model/no_circular_references.py          56      0   100.00%
material_model/referenced_material_exists.py      46      0   100.00%
-------------------------------------------------------------------------------
TOTAL                                            261     13    95.02%

py: exit 1 (7.91 seconds) /home/jdblack/documents/repos/AaC-BOM/src> nose2 -c tox.ini pid=22712
.pkg: _exit> python /home/jdblack/.local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: FAIL code 1 (8.88=setup[0.97]+cmd[7.91] seconds)
  evaluation failed :( (8.92 seconds)
```
```


### Logs

```bash
Oops...see screenshots section.
```

### Pertinent Files

Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by jondavid-black** [comment]
At first glance the issue appears to be the ```_with_validation``` function within ```_validate.,py``` raising an exception when validation fails.  If we remove the exception, this fundamentally changes the behavior of the ```validated_definitions``` function.

So we must ask, as an AaC developer do I want an exception raised as the result of running validation?
- Keep the exception:  It's likely a built-in assumption at this point that any call to ```validate_definitions``` is guaranteed to result in a valid model or an exception. This means the developer doesn't have to worry about handling invalid model definitions.  If we keep this approach, perhaps we need better top level exception handling and messaging.  Hopefully we can agree that seeing a python stack trace due to a validation failure doesn't help an end user understand how to correct the issue in their model.
- Don't keep the exception:  This would return a validation result that must be handled by the developer.  Anywhere the developer is relying on validation, an additional ```is_valid()``` check would have to be implemented along with appropriate handling.  This is a nice convenience for developers, but still results in confusing output for end users.

I have attempted to simply remove the ```raise ValidatonError``` and return the result whether validation errors occur or not.  This results in a lot of test failures.

Path forward:
- Try to update my 3rd party unit tests to expect the exception rather than a result where ```is_valid()``` returns false.
- Explore better end user CLI output in the AaC processing for '''ValidationError''' conditions.

**Comment by jondavid-black** [comment]
Step 1 of the path forward was successful...I've updated the validator unit tests to expect a ValidationError be raised upon failure of the "core validator" when providing bad data.  On to step 2.

**Comment by jondavid-black** [comment]
I've run some direct tests on the 3rd party plugin (which had to be explicitly activated, even though I pip installed it) using both valid and invalid inputs.

Good news:  
- The actual validation results are correct!
- The expected validation errors were observed in the output without stack traces!
Bad news:  
- There are a ton of "Validation INFO ..." messages.  These appear to be generated from built-in and 1st party plugin definitions, but there are a few actually referring to provided model content (although not clear why).
- The 3rd party validators are being run and reported multiple times for the same content.  I counted the same "single" expected error output 13 different times.
- Validation is slower than expected...maybe because it appears things are being repeated based on the output.

It's a bit difficult to determine the correct next step.  I'll look into the duplication and see what I can discover.

**Comment by jondavid-black** [comment]
I've confirmed the Validation INFO messages originate from the ```unused_definitions``` validator plugin.  If you disable this plug-in the output is much better. Should we disable this by default?

**Comment by jondavid-black** [comment]
I believe I've discovered the root cause for the ```aac/spec/spec.yaml``` validations errors on ```Validate definition references```.  It turns out we have two validators interacting in a way I certainly didn't expect, and it's completely related to plugin activation state.  When the ```Validate Reference Primitives``` check is run, it's looking for names in the ```language_context```.  It turns out that if you define a schema and define validation for it, the plugin which provides that validation must be active or it will not be recognized by the ```language_context```.  So in the case of ```aac/spec/spec.yaml``` where the schema for ```Schema``` contains a validation for ```Definition is referenced``` and the ```Validate definition references``` plugin is not active by default, although the validator exists it is not seen within ```language_context``` during validation.

As for the duplications, I believe I've identified the culprit for that as well.  The ```_validate_definition``` function within ```aac/validate/_validate.py``` create a list it refers to as ```all_applicable_definitions``` which consists of the ancestor and sub-structure definitions.  I don't understand the concept behind ancestor, sub-structure, or even target_schema_definition so I hesitate to recommend a fix without further discussion.  In short, I could easily eliminate the replication of validator execution by simply constraining the loops in this method to only execute validation when the definition name and the target_schema_definition names were the same.  This sped up the validation run a noticeable amount.  

So we need to figure out 2 things:
1. What should we do about plugin active/inactive state in validation?  My current thought is to change the ```Validate definition references``` to look at all definitions whether active or not and provide a warning if actively using an inactive plugin reference.
2. What should we do about ```target_schema_definition``` driven duplication in the validator?  Based on the generated argument definition, this should be "The schema definition with the validation rules that trigger the validation".  Because validation rules are driven by the validation tag in the defining schema, I would argue we've not implemented this correctly.  We should update ```_validate_definition``` to only run once passing in the definition under validation and the schema which originally defines the type of that definition.

**Comment by jondavid-black** [comment]
Following up on #2 from the previous comment, I attempted to limit the ```target_schema_definition``` used in the validator and found that it resulted in a lot of test failures.  I've tried to limit the '''target_schema_definition''' to be only those schema defining the type of the object which also results in test failures.

I'm ready to conclude the validator applicability is complex.  It appears that we've implemented the "boil ocean" strategy and just run everything on everything to "be safe".  I'm left wondering if we need a better way.  Do we?  The negative impacts seem to be slow validation runtime and validation development complexity.  Maybe we just live with these for now.

- Why is it not sufficient to just use the validators explicitly identified in the defining schema?
- Should we have a way to define a "global" validator?

So what to do about this bug?  The true origin of this bug has been resolved through the realization that the core validator will never return an invalid ```ValidatorResult```, only throw a ```ValidationError```.  Although it feels a bit like giving up, we should probably close this bug and deal with the broader validation questions separately.  We'll discuss and decide.
