### ISSUE TITLE
🐛 [BUG] - Gen-Plugin Fails

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#823]
### Pre-requisites

- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

### What version of the AaC package are you using? Check your version with the command: aac version.

0.4.8

### Description

I'm developing a project and plugin but encounter errors when running gen-plugin.  Plugin is in [AaC-Req-QA repo](https://github.com/DevOps-MBSE/AaC-Req-QA).

### Reproduction URL

https://github.com/DevOps-MBSE/AaC-Req-QA

### Reproduction steps

```bash
Please enter an explicit description of your issue
1. From the root of the repository.
2. Run the command `aac gen-plugin --code-output ./src --test-output ./tests --doc-output ./docs ./src/aac_req_qa/plugins/req_qa/req_qa.aac`
3. Enter `y` when prompted to continue.
4. See error: black.parsing.InvalidInput: Cannot parse: 19:0: <line number missing in source>
```

### Screenshots

```bash
If applicable, add screenshots to help explain your problem.
![DESCRIPTION](LINK.png)
```

### Logs

```bash
~/repos/AaC-Req-QA$ aac gen-plugin --code-output ./src --test-output ./tests --doc-output ./docs ./src/aac_req_qa/plugins/req_qa/req_qa.aac 
AaC Gen-Plugin will generate code and tests in the following directories:
   code: ./src
   tests: ./tests
   docs: ./docs
Do you want to continue? (y/n): y
Traceback (most recent call last):
  File "/home/jd/anaconda3/envs/aac-req-qa/bin/aac", line 8, in <module>
    sys.exit(cli())
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/aac/execute/command_line.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/aac/plugins/gen_plugin/__init__.py", line 74, in run_gen_plugin
    gen_plugin_generate_result = after_gen_plugin_generate(
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/aac/plugins/gen_plugin/gen_plugin_impl.py", line 57, in after_gen_plugin_generate
    return generate(
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/aac/plugins/generate/__init__.py", line 26, in run_generate
    generate_result = generate(
  File "/home/jd/anaconda3/envs/aac-req-qa/lib/python3.10/site-packages/aac/plugins/generate/generate_impl.py", line 139, in generate
    output = black.format_str(jinja_output, mode=black.Mode())
  File "src/black/__init__.py", line 1225, in format_str
  File "src/black/__init__.py", line 1239, in _format_str_once
  File "src/black/parsing.py", line 90, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 19:0: <line number missing in source>
```

### Pertinent Files

https://github.com/DevOps-MBSE/AaC-Req-QA/blob/main/src/aac_req_qa/plugins/req_qa/req_qa.aac

**Comment by jondavid-black** [comment]
It turned out I had an indentation problem in my plugin definition file.  Once I fixed that, everything worked fine.
